### ISSUE TITLE
Update xxx.yml 5/01/2018 - new branch "xxx"

### ISSUE THREAD

**Issue by xskl0** [acceptbitcoincash/acceptbitcoincash#381] opened 2018-01-05 16:18 UTC
websites premium:

  - name: Brazzers Network
      url: https://www.brazzersnetwork.com/
      twitter: Brazzers
      facebook: TheBrazzersOfficial
      img: https://images.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.wjpUc1R9oO2QaWB7TvN_JAHaDt%26pid%3D15.1&f=1 
      bch: No
      btc: 
      othercrypto: No

   - name: Digital Playground
      url: https://www.digitalplayground.com/
      twitter: dpxxx
      facebook: DigitalPlayground
      img: https://scontent-mad1-1.xx.fbcdn.net/v/t1.0-9/14317321_1176703642387288_2130224877934948008_n.jpg?oh=4a7016588c214edd6c4ff198550e1564&oe=5AFF52B9
      bch: No
      btc: 
      othercrypto: No

   - name: Babes Network
      url: https://www.babesnetwork.com
      twitter: Babes
      facebook: babesofficialpage
      img: https://pbs.twimg.com/profile_images/681891203638403072/FY7o67SG_400x400.jpg
      bch: No
      btc: 
      othercrypto: No

   - name: Family Strokes
      url: http://familystrokes.com
      twitter: familystrokes
      img: https://pbs.twimg.com/profile_images/645969080000888832/UP1Xu7wJ_400x400.jpg
      bch: No
      btc: No
      othercrypto: No

   - name: Team Skeet
      url: http://www.teamskeet.com/
      twitter: @teamskeet
      img: https://pbs.twimg.com/profile_images/864220601677996033/1r-UFkA4_400x400.jpg
      bch: No
      btc: No
      othercrypto: No

   - name: CzechAV
      url: http://www.czechav.com/
      twitter: CzechAV
      facebook: Czechav
      img: https://pbs.twimg.com/profile_images/871726156810264576/4OfE50rO_400x400.jpg
      bch: No
      btc: No
      othercrypto: No

   - name: FaKings
      url: https://www.fakings.com
      twitter: FAKingsPorno 
      img: https://pbs.twimg.com/profile_images/816923056564240384/CF9p7h5v_400x400.jpg
      bch: No
      btc: No
      othercrypto: No

   - name: Evil Angel
      url: https://www.evilangel.com
      twitter: EvilAngelvideo
      img: https://www.evilangel.com/m/bnd91nk7ojk00w8o/footerLogo.svg
      bch: No
      btc: No
      othercrypto: No

   - name: SisLovesMe
      url: http://sislovesme.com
      twitter: sislovesme
      img: https://pbs.twimg.com/profile_images/702893754793881600/NhYFrO9-_400x400.jpg
      bch: No
      btc: No
      othercrypto: No

   - name: New Sensations
      url: http://newsensations.com/
      twitter: NSDSxxx
      facebook: NewSensationsDigitalSinNSDS
      img: https://pbs.twimg.com/profile_images/821435252753108992/vLQmAJ8f_400x400.jpg
      bch: No
      btc: No
      othercrypto: No

   - name: StasyQ
      url: https://www.stasyq.com
      twitter: stasyq 
      facebook: stasyq.official 
      img: https://pbs.twimg.com/profile_images/834042337311469570/F2VtrejG_400x400.jpg
      bch: No
      btc: No
      othercrypto: No

   - name: BANG.com
      url: https://www.bang.com/
      twitter: Bang_Twts
      img: https://pbs.twimg.com/profile_images/948643832245071872/6YmZ5ri6_400x400.jpg
      bch: No
      btc: No
      othercrypto: No

    - name: Dog Fart Network
      url: http://www.dogfartnetwork.com
      img: dogfartnetwork.png
      twitter: dogfartnetwork
      bch: No
      btc: No
      othercrypto: No

    - name: Fine Love Dolls
      url: https://www.finelovedolls.com
      twitter: finelovedolls
      facebook: FineLoveDollsWorldwide
      img: finelovedolls.png
      bch: yes
      btc: yes
      othercrypto: yes

    - name: Naughty America
      url: https://www.naughtyamerica.com/
      img: naughtyamerica.png
      twitter: naughtyamerica
      bch: No
      btc: Yes
      othercrypto: No

    - name: PornHub
      url: https://www.pornhub.com/
      img: pornhub.png
      twitter: Pornhub
      bch: No
      btc: No
      othercrypto: No

    - name: Porn Pros
      url: https://pornpros.com/
      img: pornpros.png
      twitter: ProsPornVideos
      bch: No
      btc: No
      othercrypto: No

    - name: xHamster
      url: https://xhamster.com
      img: xhamster.png
      twitter: xhamstercom
      facebook: xhamsterporn
      bch: No
      btc: No
      othercrypto: No

    - name: Bang Bros
      url: https://bangbros.com/
      img: bangbros.png
      twitter: bangbrosdotcom
      bch: No
      btc: No
      othercrypto: No

    - name: BitcoinSexToys
      url: https://bitcoinsextoys.co.uk
      img: bitcoinsextoys.png
      bch: yes
      btc: yes
      othercrypto: yes

   - name: 
      url: https://www.woodmancastingx.com
      twitter: woodman_news
      facebook: pierrewoodmanofficiel
      img: 
      bch: No
      btc: Yes
      othercrypto: No

   - name: Porndoepremium
      url: https://es.porndoepremium.com/
      twitter: porndoepremium 
      facebook: PornDoePremium
      img: https://pbs.twimg.com/profile_images/868113117116596228/-9eoIVjZ_400x400.jpg
      bch: No
      btc: No
      othercrypto: No

   - name: MetArt
      url: https://www.metart.com/
      twitter: metart
      img: https://static.metart.com/view/images/responsive/nav/ma.png
      bch: No
      btc: No
      othercrypto: No

   - name: Sweetheart Video
      url: https://www.sweetheartvideo.com
      twitter: SweetHeartVids
      facebook: SweetHeartVideo
      img: https://pbs.twimg.com/profile_images/941383587131097088/Bq2MiYVu_400x400.jpg
      bch: No
      btc: No
      othercrypto: No

   - name: Web Young Official
      url: https://www.webyoung.com
      twitter: girlswaynetwork
      img: https://pbs.twimg.com/profile_images/684066733502652416/mwD211Ib_400x400.jpg
      bch: No
      btc: No
      othercrypto: No

   - name: Submissived
      url: http://submissived.com
      twitter: TeamSkeet
      img: http://cdn.teamskeetimages.com/design/tour/sub/pintour/1/default/img/logo.png
      bch: No
      btc: No
      othercrypto: No

live cams:

  - name: Chaturbate
      url: https://www.chaturbate.com
      img: chaturbate.png
      twitter: chaturbate
      bch: No
      btc: Yes
      othercrypto: No
doc: https://blog.chaturbate.com/news-and-announcements/purchase-tokens-with-bitcoin/

    - name: ImLive.com
      url: https://imlive.com/
      img: https://i4.imlmediahub.com/gimages/logonew2.gif
      twitter: ImLiveCom
      bch: No
      btc: No
      othercrypto: No 

    - name: MyFreeCams.com
      url: https://www.myfreecams.com/
      twitter: MyFreeCams
      facebook: MyFreeCams 
      img: https://pbs.twimg.com/profile_images/796494930776625152/nXqgkl3F_400x400.jpg
      bch: No
      btc: No
      othercrypto: No 

    - name: Stripchat
      url: https://stripchat.com/
      twitter: stripchat
      facebook: stripchatofficial
      img: https://pbs.twimg.com/profile_images/852508619337854976/z5t2huBL_400x400.jpg
      bch: No
      btc: No
      othercrypto: No
  
   - name: Flirt4Free
      url: https://www.flirt4free.com
      twitter: flirt4free
      facebook: Flirt4Free
      img: https://pbs.twimg.com/profile_images/925577145094610944/9N54f7Vi_400x400.jpg
      bch: No
      btc: No
      othercrypto: No

   - name: Camster
      url: https://camster.com
      twitter: camsterdotcom
      img: https://pbs.twimg.com/profile_images/778612117108826112/3qsTmQM2_400x400.jpg 
      bch: No
      btc: No
      othercrypto: No 

   - name: CamSoda
      url: https://www.camsoda.com/
      twitter: camsodalive
      facebook: CamSoda
      img: https://pbs.twimg.com/profile_images/684847687498252288/4f2WkjMV_400x400.jpg
      bch: No
      btc: No
      othercrypto: No 

   - name: XCams
      url: https://www.xcams.com/
      twitter: xcams
      facebook: Xcams
      img: https://www.facebook.com/Xcams/photos/a.621982297939025.1073741825.621981997939055/1058144900989427/?type=3&theater 
      bch: No
      btc: No
      othercrypto: No 

   - name: iFriends
      url: https://www.ifriends.net/
      twitter: ifriends
      img: https://images.ifriends.net/if_cdn/frameworks/foundation-6/dist/assets/css/ifriendsv2/logo.png
      bch: No
      btc: No
      othercrypto: No

**Comment by kenman345** [comment] 2018-01-12 16:16
We will be renaming this new page to be "Adult" shortly

**Comment by kenman345** [comment] 2018-01-24 18:15
This branch is near ready. We have not forgotten about it

**Comment by kenman345** [comment] 2018-01-30 20:34
we need to remove the xxx.yml from the branch since its now a duplicate of the adult.yml

**Closed** 2018-02-06 05:01 UTC
