### ISSUE TITLE
Add 'TheBigCoin' to the 'Crypto Services' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1309] opened 2018-10-16 20:53 UTC
Requesting to add 'TheBigCoin' to the 'Crypto Services' category. 

Details follow: 
```yml 
- name: TheBigCoin
      url: https://thebigcoin.io
      img: 
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Request made by @kenman345
Resources for adding this merchant:
Logo Provided:
![TheBigCoin](https://pbs.twimg.com/profile_images/1032208154094960640/v6YTsUkl_400x400.jpg)
[Picresize Starter Link](http://www.picresize.com/api?fetch=https://pbs.twimg.com/profile_images/1032208154094960640/v6YTsUkl_400x400.jpg)

[Link to TheBigCoin](https://thebigcoin.io)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/thebigcoin.io](https://www.alexa.com/siteinfo/thebigcoin.io)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/thebigcoin.io](https://www.scamadviser.com/check-website/thebigcoin.io)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/thebigcoin.io](https://www.trustpilot.com/review/thebigcoin.io)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

**Comment by EchterAgo** [comment] 2018-10-18 10:36
Duplicate of #1167 already added in 'Services'

**Closed by EchterAgo** 2018-10-18 10:36 UTC
Labels: new addition, web form
