### ISSUE TITLE
Add 'WK END eyewear' to the 'Sunglasses' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#517] opened 2018-02-01 16:46 UTC
Requesting to add 'WK END eyewear' to the 'Sunglasses' category. 

Details follow: 
```yml 
- name: WK END eyewear
      url: https://wkend.club/
      img: https://scontent.fsnc1-1.fna.fbcdn.net/v/t1.0-9/27336961_347226549019511_7119229417660045028_n.jpg?oh=e4f905bd4f1296d4306e486fdaa6bd0f&oe=5AEBE73C
      facebook: wkend.club
      email_address: info@wkend.club
      bch: yes
      btc: no
      othercrypto: yes
```

**Comment by kenman345** [comment] 2018-02-05 17:45
Was duplicate of another issue already added and merged in a PR

**Closed by kenman345** 2018-02-05 17:45 UTC
Labels: new addition, web form
